export const actionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  CLEAR_PRODUCT: "CLEAR_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
